### ISSUE TITLE
🤖 GitHub Bot: Rich markup error and git diff issues

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [gptme/gptme#256]
### Current Behavior
Currently experiencing two main errors when running the GitHub Bot:

1. Rich markup error:
```
ERROR:gptme.message:Error printing message
Traceback (most recent call last):
  File "/workspace/gptme/message.py", line 313, in print_msg
    console.print(s)
  File "/usr/local/lib/python3.10/site-packages/rich/console.py", line 1679, in print
    renderables = self._collect_renderables(
  File "/usr/local/lib/python3.10/site-packages/rich/console.py", line 1539, in _collect_renderables
    self.render_str(
  File "/usr/local/lib/python3.10/site-packages/rich/console.py", line 1429, in render_str
    rich_text = render_markup(
  File "/usr/local/lib/python3.10/site-packages/rich/markup.py", line 167, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/<m>]' at position 3246 doesn't match any open tag
```

2. Git diff command error:
```
error: unknown option `cached'
usage: git diff --no-index [<options>] <path> <path>
```
![image](https://github.com/user-attachments/assets/6d8ec3eb-ea8c-48fc-89c3-5f1f2e8fe041)

**Comment by ErikBjare** [comment]
The error appears when it tries to run `git diff --cached` outside of a git repo.

Can you give some more information about the setup you are using?

**Comment by Sunwood-ai-labs** [comment]
@ErikBjare Thank you for checking.

I am currently using the following GitHub Actions configurations:
- `.github/actions/bot/action.yml`: https://github.com/Sunwood-ai-labs/gptme-github-bot-demo1/blob/main/.github/actions/bot/action.yml
- `.github/workflows/bot.yml`: https://github.com/Sunwood-ai-labs/gptme-github-bot-demo1/blob/main/.github/workflows/bot.yml

Note that I have modified some parts of `action.yml` due to permission-related errors.

This is the setup where the git diff error you mentioned is occurring.

**Comment by ErikBjare** [comment]
Significant changes have been made to the GitHub Bot since this issue was opened. If issues persist, open a new issue.

**Comment by TimeToBuildBob** [comment]
Closing per Erik's comment from Dec 2025: the GitHub Bot has been significantly reworked since this was filed. If any of these issues persist with the current bot, please open a new focused issue. Thanks\!
